// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hufyvljiumthdszpnqti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1Znl2bGppdW10aGRzenBucXRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4MzI3NTgsImV4cCI6MjA4NzQwODc1OH0.If4utkjxGSK-mjOt4RxMBrNwC6Ycn7jaFPoFg_OyXoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});